url: https://yuppymam.github.io/know-one-minute/
excerpt_separator: "<!--more-->"
permalink: /:title

collections:
  category:
    output: true

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - .jekyll-cache
