url: https://yuppymam.github.io/know-one-minute/
excerpt_separator: "<!--more-->"
permalink: /:title

collections:
  category:
    output: true

plugins:
  - jekyll-last-modified-at

jekyll_admin:
  hidden_links:

defaults:
  - scope:
      layout: post
      thumbnail: ''
      categories: ''
      date: ''
      last_modified_at: ''

last-modified-at:
    date-format: '%Y-%m-%d'

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - .jekyll-cache
