url: https://know-one-minute.com/
excerpt_separator: "<!--more-->"
permalink: /:title

plugins:
  - jekyll-last-modified-at
  - jekyll-paginate

paginate: 4

collections:
  category:
    output: true

last-modified-at:
  date-format: '%Y-%m-%d'

jekyll_admin:
  hidden_links:
    - datafiles
  homepage: "posts"

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      thumbnail: "/assets/images/thumbnails/sample.png"
      categories: []
      last_modified_at: ''

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - .jekyll-cache
